# https://alacritty.org/config-alacritty.html
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600


[env]
TERM = "xterm-256color"

[font]
size = 12

[font.offset]
x = 0
y = 1

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload = true

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001f"

[mouse]
hide_when_typing = true


[scrolling]
history = 5000

[terminal]
shell = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "Both"
decorations = "Transparent"
dynamic_padding = false
opacity = 0.9
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 20
